site_name: pgEdge Starfleet (Preview)
use_directory_urls: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences

theme:
  name: material
  favicon: img/favicon.ico
  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.top
    - navigation.indexes
    - toc.follow
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - pgEdge Starfleet Managed Postgres:
    - Overview: index.md
  - Deploying a Managed Database: managed/creating_managed.md
  - Using the Database Console:
    - managed/using/index.md
    - Serving up AI Content:
      - MCP Server: managed/using/services/mcp.md
      - RAG Server: managed/using/services/rag.md
    - Monitoring System Metrics: managed/using/metrics.md
    - Reviewing the Log Files: managed/using/logs.md
    - Restoring from Backup: managed/using/backups.md
  - Accessing Management Options with the Actions Menu: managed/using/actions.md
  - Connecting to a pgEdge Starfleet Postgres Database: connecting.md
  - Loading Data into Your pgEdge Starfleet Database: loading_data.md
  - Reviewing the Activity Log: activity_log.md
  - Managing Account Settings: settings.md
  - Managing Team Members: team_management.md
  - Community: community.md
  - Docs: docs_link.md
